spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wsmhz-shop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: redis
  application:
    name: api-gateway
server:
  port: 8091
  session:
    timeout: 3600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#  # /myProduct/product/list -> /product/product/list
#    aaaaaa:
#      path: /myProduct/**
#      serviceId: product
#      sensitiveHeaders:
#  #简洁写法
##    product: /myProduct/**
#  #排除某些路由
#  ignored-patterns:
#    - /**/product/listForOrder
#management:
#  security:
#    enabled: false